#Создание нового пользователя
from selenium import webdriver
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.get("http://users.bugred.ru/")
driver.set_window_size(904, 666)
driver.find_element(By.CSS_SELECTOR, ".newlink:nth-child(2) span").click()
driver.find_element(By.NAME, "login").click()
driver.find_element(By.NAME, "login").send_keys("manager@mail.ru")
driver.find_element(By.NAME, "password").click()
driver.find_element(By.NAME, "password").send_keys("1")
driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .btn").click()
driver.find_element(By.LINK_TEXT, "Добавить пользователя").click()
driver.find_element(By.NAME, "noibiz_name").click()
driver.find_element(By.NAME, "noibiz_name").send_keys("Черепаха3")
driver.find_element(By.NAME, "noibiz_email").send_keys("3@mail.ru")
driver.find_element(By.NAME, "noibiz_password").send_keys("123")
driver.find_element(By.NAME, "noibiz_birthday").click()
driver.find_element(By.NAME, "noibiz_birthday").click()
driver.find_element(By.NAME, "noibiz_birthday").send_keys("2024-07-08")
driver.find_element(By.NAME, "noibiz_gender").click()
driver.find_element(By.NAME, "noibiz_gender")
driver.find_element(By.XPATH, "//option[. = 'Мужской']").click()
driver.find_element(By.NAME, "noibiz_date_start").click()
driver.find_element(By.NAME, "noibiz_date_start").send_keys("2024-07-05")
driver.find_element(By.NAME, "noibiz_hobby").click()
driver.find_element(By.NAME, "noibiz_hobby").send_keys("Плавать")
driver.find_element(By.NAME, "noibiz_name1").click()
driver.find_element(By.NAME, "noibiz_name1").send_keys("123")
driver.find_element(By.NAME, "noibiz_surname1").click()
driver.find_element(By.NAME, "noibiz_surname1").send_keys("123")
driver.find_element(By.CSS_SELECTOR, ".numberfilter").click()
driver.find_element(By.NAME, "noibiz_cat").click()
driver.find_element(By.NAME, "noibiz_cat").send_keys("Пушок")
driver.find_element(By.CSS_SELECTOR, ".numberfilter").send_keys("Птица")
driver.find_element(By.NAME, "noibiz_dog").click()
driver.find_element(By.NAME, "noibiz_dog").send_keys("Барбос")
driver.find_element(By.NAME, "noibiz_parrot").click()
driver.find_element(By.NAME, "noibiz_parrot").send_keys("Чиж")
driver.find_element(By.NAME, "noibiz_cavy").click()
driver.find_element(By.NAME, "noibiz_cavy").send_keys("Мими")
driver.find_element(By.NAME, "noibiz_hamster").click()
driver.find_element(By.NAME, "noibiz_hamster").send_keys("Хома")
driver.find_element(By.NAME, "noibiz_squirrel").click()
driver.find_element(By.NAME, "noibiz_squirrel").send_keys("Чип")
driver.find_element(By.NAME, "noibiz_phone").click()
driver.find_element(By.NAME, "noibiz_phone").send_keys("1415")
driver.find_element(By.NAME, "noibiz_adres").click()
driver.find_element(By.NAME, "noibiz_adres").send_keys("Край")
driver.find_element(By.NAME, "noibiz_inn").click()
driver.find_element(By.NAME, "noibiz_inn").send_keys("123456")
driver.find_element(By.NAME, "act_create").click()
#Логин под новым пользователем
driver.find_element(By.LINK_TEXT, "Злобный босс").click()
driver.find_element(By.LINK_TEXT, "Выход").click()
driver.find_element(By.CSS_SELECTOR, ".newlink:nth-child(2) span").click()
driver.find_element(By.NAME, "login").click()
driver.find_element(By.NAME, "login").send_keys("3@mail.ru")
driver.find_element(By.NAME, "password").click()
driver.find_element(By.NAME, "password").send_keys("123")
driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .btn").click()
#Поиск и удаление пользователя
driver.find_element(By.NAME, "q").click()
driver.find_element(By.NAME, "q").send_keys("Черепаха3")
driver.find_element(By.CSS_SELECTOR, ".btn-submit").click()
driver.find_element(By.LINK_TEXT, "Посмотреть").click()
driver.find_element(By.LINK_TEXT, "Черепаха3").click()
driver.find_element(By.LINK_TEXT, "Выход").click()
driver.find_element(By.CSS_SELECTOR, ".newlink:nth-child(2) span").click()
driver.find_element(By.NAME, "login").click()
driver.find_element(By.NAME, "login").send_keys("manager@mail.ru")
driver.find_element(By.NAME, "password").click()
driver.find_element(By.NAME, "password").send_keys("1")
driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) .btn").click()
driver.find_element(By.NAME, "q").click()
driver.find_element(By.NAME, "q").send_keys("Черепаха3")
driver.find_element(By.CSS_SELECTOR, ".btn-submit").click()
driver.find_element(By.LINK_TEXT, "Удалить").click()